FROM ubuntu:16.04
RUN apt-get -y update && apt-get install -y nano python python-pip 
RUN pip install numpy scipy matplotlib scikit-image scikit-learn
# Uncomment and change path to append 2-way binded volume
# RUN mkdir /docker-volume
# VOLUME /docker-volume 
