FROM ubuntu:16.04
RUN apt-get -y update && apt-get install -y nano python3 python3-pip 
RUN pip3 install numpy scipy matplotlib scikit-image scikit-learn
# Uncomment and change path to append 2-way binded volume
# RUN mkdir /docker-volume
# VOLUME /docker-volume 
