FROM ubuntu:16.04
RUN apt-get -y update && apt-get install -y nano python3.5 python3-pip 
RUN apt-get -y install python3-dev
RUN pip3 install numpy scipy matplotlib scikit-image scikit-learn cython
# Uncomment and change path to append 2-way binded volume
# RUN mkdir /docker-volume
# VOLUME /docker-volume 
