# From docker with cuda
FROM nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04 

# Install python2.8 & python3.5
RUN apt-get -y update && apt-get install -y nano python2.8 python-pip python-dev
RUN apt-get -y update && apt-get install -y nano python3.5 python3-pip python3-dev
RUN pip install numpy scipy matplotlib scikit-image scikit-learn cython
RUN pip3 install numpy scipy matplotlib scikit-image scikit-learn cython
